configurations:
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/DevSettingsUseCase
    templates:
      - Templates/AutomaticSettings/AutomaticSettings.stencil
    output: ../../FireModules/Sources/Features/SettingsFeature/CodeGen/
    baseIndentation: 4
    args:
      settingsView: DevSettingsView
      settingsStructure: DevSettings
      settingsExternalData: DevSettingsExternalData
      settingsImports:
        - DevSettingsUseCase
  - sources:
      include:
        - ../../FireModules/Sources/Domains/DataInterfaces/PersistenceServiceInterface
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Data/PersistenceService/Generated/
    baseIndentation: 4
    args:
      autoMockableImports:
        - PersistenceServiceInterface
        - DomainEntities
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/LogInUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/LogInUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/TransactionListUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/TransactionListUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/FundListUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/FundListUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/PortfolioUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/PortfolioUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/FundCreationUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/FundCreationUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/FundDetailsUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/FundDetailsUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/AccountRegisterUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/AccountRegisterUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/TransactionRecordUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/TransactionRecordUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/InvestmentUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/InvestmentUseCase/Generated
    baseIndentation: 4
  - sources:
      include:
        - ../../FireModules/Sources/Domains/UseCases/LiveMarketUseCase
    templates:
      - Templates/AutoMockable/AutoMockable.stencil
    output: ../../FireModules/Sources/Domains/UseCases/LiveMarketUseCase/Generated
    baseIndentation: 4




  
