// swiftlint:disable superfluous_disable_command
// swiftlint:disable line_length
// swiftlint:disable file_length
// swiftlint:disable vertical_whitespace
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen
// DO NOT modify this file directly


public extension PlatformColor {
    struct CoreUI {
        /// #A0E1E1 (r: 160, g: 225, b: 225, a: 255)
        public var brightBlue: PlatformColor { #colorLiteral(red: 0.627451, green: 0.88235295, blue: 0.88235295, alpha: 1.0) }
        /// #9FE870 (r: 159, g: 232, b: 112, a: 255)
        public var brightGreen: PlatformColor { #colorLiteral(red: 0.62352943, green: 0.9098039, blue: 0.4392157, alpha: 1.0) }
        /// #FFC091 (r: 255, g: 192, b: 145, a: 255)
        public var brightOrange: PlatformColor { #colorLiteral(red: 1.0, green: 0.7529412, blue: 0.5686275, alpha: 1.0) }
        /// #FFD7EF (r: 255, g: 215, b: 239, a: 255)
        public var brightPink: PlatformColor { #colorLiteral(red: 1.0, green: 0.84313726, blue: 0.9372549, alpha: 1.0) }
        /// #FFEB69 (r: 255, g: 235, b: 105, a: 255)
        public var brightYellow: PlatformColor { #colorLiteral(red: 1.0, green: 0.92156863, blue: 0.4117647, alpha: 1.0) }
        /// #0E0F0C (r: 14, g: 15, b: 12, a: 255)
        public var contentPrimary: PlatformColor { #colorLiteral(red: 0.05490196, green: 0.05882353, blue: 0.047058824, alpha: 1.0) }
        /// #21231D (r: 33, g: 35, b: 29, a: 255)
        public var darkCharcoal: PlatformColor { #colorLiteral(red: 0.12941177, green: 0.13725491, blue: 0.11372549, alpha: 1.0) }
        /// #3A341C (r: 58, g: 52, b: 28, a: 255)
        public var darkGold: PlatformColor { #colorLiteral(red: 0.22745098, green: 0.20392157, blue: 0.10980392, alpha: 1.0) }
        /// #320707 (r: 50, g: 7, b: 7, a: 255)
        public var darkMaroon: PlatformColor { #colorLiteral(red: 0.19607843, green: 0.02745098, blue: 0.02745098, alpha: 1.0) }
        /// #260A2F (r: 38, g: 10, b: 47, a: 255)
        public var darkPurple: PlatformColor { #colorLiteral(red: 0.14901961, green: 0.039215688, blue: 0.18431373, alpha: 1.0) }
        /// #163300 (r: 22, g: 51, b: 0, a: 255)
        public var forestGreen: PlatformColor { #colorLiteral(red: 0.08627451, green: 0.2, blue: 0.0, alpha: 1.0) }
        /// #A8200D (r: 168, g: 32, b: 13, a: 255)
        public var sentimentNegative: PlatformColor { #colorLiteral(red: 0.65882355, green: 0.1254902, blue: 0.050980393, alpha: 1.0) }
        /// #2F5711 (r: 47, g: 87, b: 17, a: 255)
        public var sentimentPositive: PlatformColor { #colorLiteral(red: 0.18431373, green: 0.34117648, blue: 0.06666667, alpha: 1.0) }
        /// #EDC843 (r: 237, g: 200, b: 67, a: 255)
        public var sentimentWarning: PlatformColor { #colorLiteral(red: 0.92941177, green: 0.78431374, blue: 0.2627451, alpha: 1.0) }

        /// A collection of all custom colors generated by BECoreUI
        public var allColors: [PlatformColor] {
            return [brightBlue, brightGreen, brightOrange, brightPink, brightYellow, contentPrimary, darkCharcoal, darkGold, darkMaroon, darkPurple, forestGreen, sentimentNegative, sentimentPositive, sentimentWarning]
        }
    }
}

public extension Color {
	struct CoreUI {
		/// #A0E1E1 (r: 160, g: 225, b: 225, a: 255)
		public var brightBlue: Color { Color(#colorLiteral(red: 0.627451, green: 0.88235295, blue: 0.88235295, alpha: 1.0)) }
		/// #9FE870 (r: 159, g: 232, b: 112, a: 255)
		public var brightGreen: Color { Color(#colorLiteral(red: 0.62352943, green: 0.9098039, blue: 0.4392157, alpha: 1.0)) }
		/// #FFC091 (r: 255, g: 192, b: 145, a: 255)
		public var brightOrange: Color { Color(#colorLiteral(red: 1.0, green: 0.7529412, blue: 0.5686275, alpha: 1.0)) }
		/// #FFD7EF (r: 255, g: 215, b: 239, a: 255)
		public var brightPink: Color { Color(#colorLiteral(red: 1.0, green: 0.84313726, blue: 0.9372549, alpha: 1.0)) }
		/// #FFEB69 (r: 255, g: 235, b: 105, a: 255)
		public var brightYellow: Color { Color(#colorLiteral(red: 1.0, green: 0.92156863, blue: 0.4117647, alpha: 1.0)) }
		/// #0E0F0C (r: 14, g: 15, b: 12, a: 255)
		public var contentPrimary: Color { Color(#colorLiteral(red: 0.05490196, green: 0.05882353, blue: 0.047058824, alpha: 1.0)) }
		/// #21231D (r: 33, g: 35, b: 29, a: 255)
		public var darkCharcoal: Color { Color(#colorLiteral(red: 0.12941177, green: 0.13725491, blue: 0.11372549, alpha: 1.0)) }
		/// #3A341C (r: 58, g: 52, b: 28, a: 255)
		public var darkGold: Color { Color(#colorLiteral(red: 0.22745098, green: 0.20392157, blue: 0.10980392, alpha: 1.0)) }
		/// #320707 (r: 50, g: 7, b: 7, a: 255)
		public var darkMaroon: Color { Color(#colorLiteral(red: 0.19607843, green: 0.02745098, blue: 0.02745098, alpha: 1.0)) }
		/// #260A2F (r: 38, g: 10, b: 47, a: 255)
		public var darkPurple: Color { Color(#colorLiteral(red: 0.14901961, green: 0.039215688, blue: 0.18431373, alpha: 1.0)) }
		/// #163300 (r: 22, g: 51, b: 0, a: 255)
		public var forestGreen: Color { Color(#colorLiteral(red: 0.08627451, green: 0.2, blue: 0.0, alpha: 1.0)) }
		/// #A8200D (r: 168, g: 32, b: 13, a: 255)
		public var sentimentNegative: Color { Color(#colorLiteral(red: 0.65882355, green: 0.1254902, blue: 0.050980393, alpha: 1.0)) }
		/// #2F5711 (r: 47, g: 87, b: 17, a: 255)
		public var sentimentPositive: Color { Color(#colorLiteral(red: 0.18431373, green: 0.34117648, blue: 0.06666667, alpha: 1.0)) }
		/// #EDC843 (r: 237, g: 200, b: 67, a: 255)
		public var sentimentWarning: Color { Color(#colorLiteral(red: 0.92941177, green: 0.78431374, blue: 0.2627451, alpha: 1.0)) }

		/// A collection of all custom colors generated by BECoreUI
		public var allColors: [Color] {
			return [brightBlue, brightGreen, brightOrange, brightPink, brightYellow, contentPrimary, darkCharcoal, darkGold, darkMaroon, darkPurple, forestGreen, sentimentNegative, sentimentPositive, sentimentWarning]
		}
	}
}

public extension PlatformColor {
    static let coreui = CoreUI()

    /// A collection of all custom color description generated by BECoreUI
    var allCoreUIColorDescription: [ColorDescription] {
        return [
            ColorDescription(name: "brightBlue", color: PlatformColor.coreui.brightBlue),
            ColorDescription(name: "brightGreen", color: PlatformColor.coreui.brightGreen),
            ColorDescription(name: "brightOrange", color: PlatformColor.coreui.brightOrange),
            ColorDescription(name: "brightPink", color: PlatformColor.coreui.brightPink),
            ColorDescription(name: "brightYellow", color: PlatformColor.coreui.brightYellow),
            ColorDescription(name: "contentPrimary", color: PlatformColor.coreui.contentPrimary),
            ColorDescription(name: "darkCharcoal", color: PlatformColor.coreui.darkCharcoal),
            ColorDescription(name: "darkGold", color: PlatformColor.coreui.darkGold),
            ColorDescription(name: "darkMaroon", color: PlatformColor.coreui.darkMaroon),
            ColorDescription(name: "darkPurple", color: PlatformColor.coreui.darkPurple),
            ColorDescription(name: "forestGreen", color: PlatformColor.coreui.forestGreen),
            ColorDescription(name: "sentimentNegative", color: PlatformColor.coreui.sentimentNegative),
            ColorDescription(name: "sentimentPositive", color: PlatformColor.coreui.sentimentPositive),
            ColorDescription(name: "sentimentWarning", color: PlatformColor.coreui.sentimentWarning)
        ]
    }
}

public extension Color {
    static let coreui = CoreUI()

    /// A collection of all custom color description generated by BECoreUI
    var allCoreUIColorDescription: [ColorDescription] {
        return [
            ColorDescription(name: "brightBlue", color: PlatformColor.coreui.brightBlue),
            ColorDescription(name: "brightGreen", color: PlatformColor.coreui.brightGreen),
            ColorDescription(name: "brightOrange", color: PlatformColor.coreui.brightOrange),
            ColorDescription(name: "brightPink", color: PlatformColor.coreui.brightPink),
            ColorDescription(name: "brightYellow", color: PlatformColor.coreui.brightYellow),
            ColorDescription(name: "contentPrimary", color: PlatformColor.coreui.contentPrimary),
            ColorDescription(name: "darkCharcoal", color: PlatformColor.coreui.darkCharcoal),
            ColorDescription(name: "darkGold", color: PlatformColor.coreui.darkGold),
            ColorDescription(name: "darkMaroon", color: PlatformColor.coreui.darkMaroon),
            ColorDescription(name: "darkPurple", color: PlatformColor.coreui.darkPurple),
            ColorDescription(name: "forestGreen", color: PlatformColor.coreui.forestGreen),
            ColorDescription(name: "sentimentNegative", color: PlatformColor.coreui.sentimentNegative),
            ColorDescription(name: "sentimentPositive", color: PlatformColor.coreui.sentimentPositive),
            ColorDescription(name: "sentimentWarning", color: PlatformColor.coreui.sentimentWarning)
        ]
    }
}

public struct ColorDescription {
    public let name: String
    public let color: PlatformColor
}

// swiftlint:enable line_length
// swiftlint:enable file_length
// swiftlint:enable vertical_whitespace
// swiftlint:enable superfluous_disable_command
